import { useEffect, useState } from 'react';
import { Link, Route, Routes } from 'react-router-dom';
import type { LeadForm, SearchResponse } from './types';
import { submitLead } from './api';

const initial: LeadForm = {
  transactionType:'rent', fullName:'', email:'', phone:'', tenants:1, hasPets:false, petDetails:'', moveInDate:'', contractMonths:12,
  propertyType:'house', furnished:'indifferent', floors:'indifferent', bedrooms:2, bathrooms:1, parking:1, yard:false, garden:false, pool:false,
  amenities:[], invoiceRequired:false, guarantee:'advice', delivery:'indifferent', paymentMethod:'credit', creditPreapproved:false, creditAmount:0,
  landAreaMin:0, constructionAreaMin:0, city:'', neighborhood1:'', neighborhood2:'', neighborhood3:'', budgetMin:0, budgetMax:0,
  essentialText:'', desirableText:'', comments:'', privacyAccepted:false, contactAccepted:false, website:''
};
const money = new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:0});

function Layout({children}:{children:React.ReactNode}){
  return <><header><Link className="brand" to="/"><b>CI</b><span>Círculo Internacional<br/>de Bienes Raíces</span></Link><nav><Link to="/">Buscar</Link><Link to="/privacidad">Privacidad</Link><Link to="/admin">Administración</Link></nav></header><main>{children}</main><footer>Precios, condiciones y disponibilidad sujetos a confirmación.</footer></>;
}

function Home(){
  const [step,setStep]=useState(0); const [form,setForm]=useState<LeadForm>(()=>{try{return JSON.parse(localStorage.getItem('circulo-draft')||'null')||initial}catch{return initial}});
  const [result,setResult]=useState<SearchResponse|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
  useEffect(()=>localStorage.setItem('circulo-draft',JSON.stringify(form)),[form]);
  const set=(key:keyof LeadForm,value:unknown)=>setForm(v=>({...v,[key]:value}));
  const validate=()=>{
    if(!form.fullName.trim()||!form.email.includes('@')||form.phone.trim().length<8) return 'Completa nombre, correo y teléfono.';
    if(!form.city.trim()||form.budgetMax<=0) return 'Indica ubicación y presupuesto máximo.';
    if(form.budgetMax<form.budgetMin) return 'El presupuesto máximo debe ser mayor al mínimo.';
    if(form.hasPets&&!form.petDetails.trim()) return 'Describe las mascotas.';
    if(!form.privacyAccepted||!form.contactAccepted) return 'Debes aceptar privacidad, términos y contacto.';
    return '';
  };
  const send=async()=>{const issue=validate();if(issue){setError(issue);return}setBusy(true);setError('');try{let key=localStorage.getItem('circulo-idempotency');if(!key){key=crypto.randomUUID();localStorage.setItem('circulo-idempotency',key)}setResult(await submitLead(form,key));scrollTo({top:0,behavior:'smooth'})}catch(e){setError(e instanceof Error?e.message:'No fue posible analizar la solicitud.')}finally{setBusy(false)}};
  const restart=()=>{localStorage.removeItem('circulo-idempotency');setResult(null);setStep(1)};
  if(result) return <Results data={result} restart={restart}/>;
  return <div className="wrap"><section className="hero"><div><span className="tag">Asesoría inmobiliaria guiada</span><h1>Busca una propiedad con criterios que sí puedan existir en el mercado.</h1><p>Definimos tus prioridades, contrastamos el catálogo disponible y explicamos qué variables conviene ajustar.</p></div><aside><b>Un proceso claro, un solo canal</b><p>Al utilizar el servicio das preferencia al acompañamiento profesional y procuras evitar búsquedas redundantes. Esto no constituye exclusividad automática.</p></aside></section>
  <section className="card"><div className="progress"><span>Paso {step+1} de 4</span><i style={{width:`${(step+1)*25}%`}}/></div>
  {step===0&&<div><h2>¿Qué operación necesitas?</h2><div className="choices"><button className={form.transactionType==='rent'?'active':''} onClick={()=>set('transactionType','rent')}>Quiero rentar</button><button className={form.transactionType==='buy'?'active':''} onClick={()=>set('transactionType','buy')}>Quiero comprar</button></div></div>}
  {step===1&&<div><h2>Datos de contacto</h2><div className="grid"><Field label="Nombre completo"><input value={form.fullName} onChange={e=>set('fullName',e.target.value)}/></Field><Field label="Correo"><input type="email" value={form.email} onChange={e=>set('email',e.target.value)}/></Field><Field label="Teléfono / WhatsApp"><input value={form.phone} onChange={e=>set('phone',e.target.value)}/></Field></div></div>}
  {step===2&&<div><h2>Características del inmueble</h2><div className="grid"><Field label="Tipo"><select value={form.propertyType} onChange={e=>set('propertyType',e.target.value)}><option value="house">Casa</option><option value="apartment">Departamento</option>{form.transactionType==='buy'&&<option value="land">Terreno</option>}</select></Field><Field label="Recámaras mínimas"><input type="number" min="0" value={form.bedrooms} onChange={e=>set('bedrooms',+e.target.value)}/></Field><Field label="Baños mínimos"><input type="number" min="0" step="0.5" value={form.bathrooms} onChange={e=>set('bathrooms',+e.target.value)}/></Field><Field label="Estacionamientos"><input type="number" min="0" value={form.parking} onChange={e=>set('parking',+e.target.value)}/></Field></div><div className="checks"><Check label="Patio" value={form.yard} change={v=>set('yard',v)}/><Check label="Jardín" value={form.garden} change={v=>set('garden',v)}/><Check label="Alberca" value={form.pool} change={v=>set('pool',v)}/><Check label="Tengo mascotas" value={form.hasPets} change={v=>set('hasPets',v)}/></div>{form.hasPets&&<Field label="Raza, cantidad y tamaño"><input value={form.petDetails} onChange={e=>set('petDetails',e.target.value)}/></Field>}{form.transactionType==='rent'?<div className="grid"><Field label="Fecha de inicio"><input type="date" value={form.moveInDate} onChange={e=>set('moveInDate',e.target.value)}/></Field><Field label="Duración en meses"><input type="number" value={form.contractMonths} onChange={e=>set('contractMonths',+e.target.value)}/></Field></div>:<div className="grid"><Field label="Forma de pago"><select value={form.paymentMethod} onChange={e=>set('paymentMethod',e.target.value)}><option value="credit">Crédito</option><option value="cash">Contado</option><option value="mixed">Combinado</option></select></Field><Field label="Entrega"><select value={form.delivery} onChange={e=>set('delivery',e.target.value)}><option value="indifferent">Indistinto</option><option value="presale">Preventa</option><option value="immediate">Entrega inmediata</option></select></Field></div>}</div>}
  {step===3&&<div><h2>Ubicación y presupuesto</h2><div className="grid"><Field label="Ciudad o municipio"><input value={form.city} onChange={e=>set('city',e.target.value)}/></Field><Field label="Colonia 1"><input value={form.neighborhood1} onChange={e=>set('neighborhood1',e.target.value)}/></Field><Field label="Colonia 2"><input value={form.neighborhood2} onChange={e=>set('neighborhood2',e.target.value)}/></Field><Field label="Colonia 3"><input value={form.neighborhood3} onChange={e=>set('neighborhood3',e.target.value)}/></Field><Field label="Presupuesto mínimo MXN"><input type="number" value={form.budgetMin} onChange={e=>set('budgetMin',+e.target.value)}/></Field><Field label="Presupuesto máximo MXN"><input type="number" value={form.budgetMax} onChange={e=>set('budgetMax',+e.target.value)}/></Field></div><Field label="Indispensables"><textarea value={form.essentialText} onChange={e=>set('essentialText',e.target.value)}/></Field><Field label="Deseables / extras"><textarea value={form.desirableText} onChange={e=>set('desirableText',e.target.value)}/></Field><div className="consent"><Check label="Acepto el Aviso de Privacidad y los Términos" value={form.privacyAccepted} change={v=>set('privacyAccepted',v)}/><Check label="Autorizo contacto por correo o WhatsApp" value={form.contactAccepted} change={v=>set('contactAccepted',v)}/></div></div>}
  {error&&<p className="error">{error}</p>}<div className="actions">{step>0&&<button className="secondary" onClick={()=>setStep(step-1)}>Regresar</button>}{step<3?<button onClick={()=>setStep(step+1)}>Continuar</button>:<button disabled={busy} onClick={send}>{busy?'Analizando…':'Buscar opciones'}</button>}</div></section></div>;
}

function Results({data,restart}:{data:SearchResponse;restart:()=>void}){return <div className="wrap results"><section className="resultHead"><span className="tag">Análisis completado</span><h1>{data.analysis.headline}</h1><p>{data.analysis.explanation}</p><div className="stats"><b>{data.metrics.completeness}% completa</b><b>{data.matches.length} coincidencias</b><b>{data.analysisSource==='openai'?'IA + reglas':'Reglas'}</b></div></section>{data.matches.length?<section><h2>Opciones compatibles</h2><div className="properties">{data.matches.map(p=><article key={p.id}><span className="score">{p.matchScore}%</span>{p.demo&&<small>Demostración</small>}<h3>{p.title}</h3><p>{p.neighborhood}, {p.city}</p><strong>{money.format(p.price)}</strong><p>{p.bedrooms} rec. · {p.bathrooms} baños · {p.constructionArea||p.landArea} m²</p><ul>{p.reasons.slice(0,3).map(x=><li key={x}>{x}</li>)}</ul><em>{p.availabilityLabel}</em>{p.sourceUrl&&p.sourceUrl!=='#'&&<a href={p.sourceUrl} target="_blank" rel="noreferrer">Ver propiedad</a>}</article>)}</div></section>:<section className="card"><h2>No encontramos una coincidencia suficiente</h2><p>{data.analysis.pressurePoints.join(' ')||'La combinación actual requiere ampliar alguno de los criterios.'}</p></section>}<section className="card"><h2>Alternativas recomendadas</h2><ul>{data.analysis.suggestions.map(s=><li key={s}>{s}</li>)}</ul><div className="links">{data.externalSearchLinks.map(l=><a key={l.name} href={l.url} target="_blank" rel="noreferrer">Buscar en {l.name}</a>)}</div></section><section className="final"><h2>{data.message}</h2><p>{data.disclaimer}</p><button onClick={restart}>Reconfigurar búsqueda</button></section></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="field"><span>{label}</span>{children}</label>}
function Check({label,value,change}:{label:string;value:boolean;change:(v:boolean)=>void}){return <label className="check"><input type="checkbox" checked={value} onChange={e=>change(e.target.checked)}/><span>{label}</span></label>}
function Legal({terms=false}:{terms?:boolean}){return <article className="wrap legal"><span className="tag">Información legal</span><h1>{terms?'Términos del Servicio':'Aviso de Privacidad'}</h1><p><b>Texto provisional: revisar con asesor legal antes de publicar.</b></p>{terms?<><p>La aplicación es una herramienta de precalificación. Los resultados no garantizan disponibilidad, precio, situación jurídica ni cierre de operación.</p><p>La preferencia de asesoramiento no crea exclusividad contractual automática.</p></>:<><p>Los datos se utilizan para analizar la solicitud, contactar al interesado, presentar opciones y dar seguimiento.</p><p>El usuario podrá solicitar acceso, rectificación, cancelación u oposición mediante el canal oficial de la inmobiliaria.</p></>}<Link to="/">Volver</Link></article>}
function Admin(){return <div className="wrap"><section className="card"><span className="tag">Administración</span><h1>Fuentes inmobiliarias</h1><p>El backend incluye 14 proveedores configurables y endpoints protegidos para editar fuentes e importar CSV/JSON.</p><p>Configura <code>ADMIN_PASSWORD_HASH</code> y <code>SESSION_SECRET</code> en Render. La administración avanzada puede realizarse mediante la API documentada en el README.</p></section></div>}
export default function App(){return <Layout><Routes><Route path="/" element={<Home/>}/><Route path="/privacidad" element={<Legal/>}/><Route path="/terminos" element={<Legal terms/>}/><Route path="/admin" element={<Admin/>}/></Routes></Layout>}
