import type { ReactNode } from 'react';
import { Link } from 'react-router-dom';

export function Privacy() {
  return <Legal title="Aviso de Privacidad Integral">
    <section><h2>1. RESPONSABLE DEL TRATAMIENTO DE SUS DATOS PERSONALES</h2><p>Círculo Internacional de Bienes Raíces (en adelante “El Responsable”), con domicilio fiscal en Majahua 96 Playa Dorada, Alvarado, Veracruz, es responsable del tratamiento de sus datos personales. Para cualquier duda o trámite relacionado con el presente aviso, puede contactarnos a través del correo electrónico: <a href="mailto:circulointernacional1@gmail.com">circulointernacional1@gmail.com</a> o al teléfono <a href="tel:+522294648962">229 4648962</a>.</p></section>
    <section><h2>2. DATOS PERSONALES RECABADOS</h2><p>Para las finalidades descritas en el presente aviso, recabaremos los siguientes datos personales:</p><p>Fecha de nacimiento, Clave Única de Registro de Población (CURP), Registro Federal de Contribuyentes (RFC), identificación oficial.</p></section>
    <section><h2>3. FINALIDADES DEL TRATAMIENTO</h2><p>Los datos personales recabados serán utilizados para las siguientes finalidades:</p><h3>Primarias (Necesarias para el propósito principal de la relación):</h3><ul><li>Prestación de servicios contratados / Venta de productos</li><li>Emisión de facturas y comprobantes fiscales</li><li>Cumplimiento de obligaciones legales</li></ul><h3>Secundarias (No son estrictamente necesarias, requieren consentimiento expreso):</h3><ul><li>Envío de publicidad y promociones sobre nuestros productos/servicios</li><li>Elaboración de perfiles de clientes y estudios de mercado</li></ul><p>En caso de que no desee que sus datos personales sean tratados para estas finalidades secundarias, por favor indíquelo enviando un correo a la dirección mencionada en el apartado 1.</p></section>
    <section><h2>4. TRANSFERENCIA DE DATOS</h2><p>Sus datos personales no serán transferidos a terceros, salvo que sea necesario para cumplir con obligaciones legales o cuando se trate de empresas subsidiarias o afiliadas bajo el control del mismo Responsable.</p><p>Sus datos personales podrán ser transferidos a terceros, tanto nacionales como extranjeros, para las finalidades antes señaladas. Específicamente, sus datos podrán ser compartidos con: Proveedores de servicios de paquetería, plataformas de pago. En todos los casos, se exigirá a los terceros el cumplimiento de la LFPDPPP.</p></section>
    <section><h2>5. DERECHOS ARCO (Acceso, Rectificación, Cancelación y Oposición)</h2><p>Usted tiene derecho a saber qué datos personales tenemos de usted, a que se rectifiquen si están incorrectos o desactualizados, a solicitar su cancelación cuando ya no sean necesarios para las finalidades que fueron recabados, y a oponerse al tratamiento de los mismos para fines específicos.</p><p>Para ejercer sus derechos ARCO, deberá presentar una solicitud en el correo electrónico <a href="mailto:circulointernacional1@gmail.com">circulointernacional1@gmail.com</a> o en el domicilio antes señalado, acompañada de los siguientes documentos:</p><ul><li>Solicitud por escrito firmada por el titular</li><li>Copia de identificación oficial vigente</li><li>Descripción clara del dato personal sobre el que se pretende ejercer el derecho</li><li>Cualquier otro elemento que facilite la localización de los datos</li></ul><p>El Responsable tendrá un plazo máximo de 20 días hábiles para responder a su solicitud y, en caso de proceder, se atenderá en un plazo de 15 días hábiles siguientes a la respuesta.</p></section>
    <section><h2>6. REVOCACIÓN DEL CONSENTIMIENTO</h2><p>Usted puede revocar en cualquier momento el consentimiento que ha otorgado para el tratamiento de sus datos personales, sin que ello sea retroactivo. Para ello, deberá seguir el mismo procedimiento señalado en el apartado anterior. La revocación del consentimiento no implicará la conclusión de la relación jurídica existente ni el incumplimiento de obligaciones pendientes.</p></section>
    <section><h2>7. LIMITACIÓN DE USO Y DIVULGACIÓN DE DATOS</h2><p>El Responsable se compromete a no vender o ceder sus datos personales a ninguna empresa, organización o individuo que no esté relacionado con las finalidades autorizadas en este Aviso de Privacidad.</p></section>
    <section><h2>8. MEDIDAS DE SEGURIDAD</h2><p>Hemos adoptado las medidas de seguridad administrativas, técnicas y físicas necesarias para proteger sus datos personales contra daño, pérdida, alteración, destrucción, uso, acceso o tratamiento no autorizado, de conformidad con lo establecido en la LFPDPPP.</p></section>
    <section><h2>9. CAMBIOS AL AVISO DE PRIVACIDAD</h2><p>El Responsable se reserva el derecho de modificar el presente Aviso de Privacidad. Cualquier cambio será publicado en <a href="https://www.circulointernacionaldebienesraices.com/aviso-de-privacidad" target="_blank" rel="noreferrer">www.circulointernacionaldebienesraices.com/aviso-de-privacidad</a>. Le recomendamos revisar periódicamente este aviso para estar informado sobre cualquier actualización.</p></section>
    <section><h2>10. CONSENTIMIENTO</h2><p>Al proporcionar sus datos personales a través de www.circulointernacionaldebienesraices.com/aviso-de-privacidad, usted declara haber leído, entendido y aceptado los términos y condiciones del presente Aviso de Privacidad Integral.</p></section>
    <p className="privacy-date"><strong>Fecha de última actualización: 13 de julio de 2026.</strong></p>
  </Legal>;
}
export function Terms() { return <Legal title="Términos del Servicio"><p><strong>Texto provisional: revisar con asesor legal.</strong></p><p>La aplicación es una herramienta de precalificación y búsqueda. Sus resultados dependen de las fuentes configuradas y no garantizan disponibilidad, precio, estado jurídico ni cierre de operación.</p><h2>Coordinación del servicio</h2><p>El usuario acepta mantener un canal claro con el asesor y procurar evitar gestiones duplicadas. Esta declaración no crea exclusividad automática ni sustituye un contrato firmado.</p><h2>Información de terceros</h2><p>Todo anuncio, precio, fotografía y condición deberá verificarse con el propietario, anunciante o asesor antes de tomar decisiones.</p></Legal>; }
export function Legal({ title, children }: { title: string; children: ReactNode }) { return <article className="legal page-shell"><span className="eyebrow">Información legal</span><h1>{title}</h1>{children}<Link className="button ghost" to="/">Volver a la búsqueda</Link></article>; }
