import { Controller, type UseFormReturn } from 'react-hook-form';
import type { LeadForm, TransactionType } from './types';
import { Choice, Field, Summary, Toggle } from './FormParts';
import { labelProperty, money } from './formConfig';

type CurrencyName = 'budgetMin' | 'budgetMax' | 'creditAmount';
function CurrencyField({ form, name, label }: { form: UseFormReturn<LeadForm>; name: CurrencyName; label: string }) {
  const error = form.formState.errors[name]?.message;
  return <Field label={label} error={error}><Controller control={form.control} name={name} render={({ field }) => <input inputMode="numeric" placeholder="$ 0" value={field.value ? '$ ' + new Intl.NumberFormat('es-MX').format(Number(field.value)) : ''} onChange={event => field.onChange(Number(event.target.value.replace(/[^\d]/g, '')) || 0)} onBlur={field.onBlur} aria-label={label} />} /></Field>;
}

export function StepMode({ value, onChange }: { value: TransactionType; onChange: (value: TransactionType) => void }) {
  return <div><span className="section-kicker">Tu objetivo</span><h2>¿Quieres comprar o rentar?</h2><p className="muted">Comienza por la operación. Al final podrás ver opciones y decidir si deseas hablar con un asesor.</p><div className="choice-grid two"><Choice active={value === 'rent'} title="Quiero rentar" text="Encuentra un inmueble y compara su renta mensual." onClick={() => onChange('rent')} /><Choice active={value === 'buy'} title="Quiero comprar" text="Compara propiedades en venta dentro de tu presupuesto." onClick={() => onChange('buy')} /></div></div>;
}

export function StepProperty({ form, type, propertyType, hasPets, payment }: { form: UseFormReturn<LeadForm>; type: TransactionType; propertyType: string; hasPets: boolean; payment?: string }) {
  const { register, formState: { errors } } = form;
  const residential = ['house', 'apartment'].includes(propertyType);
  const amenities = ['Seguridad', 'Gimnasio', 'Elevador', 'Casa club', 'Vista al mar', 'Área social'];
  return <div><span className="section-kicker">La propiedad</span><h2>¿Qué necesitas que tenga?</h2><p className="muted">Indica los mínimos que sí necesitas. Lo que marques como indispensable se comparará con los datos publicados.</p>
    <div className="form-grid"><Field label="Tipo de inmueble"><select {...register('propertyType')}><option value="house">Casa</option><option value="apartment">Departamento</option><option value="land">Terreno</option><option value="retail">Local</option><option value="office">Oficina</option><option value="warehouse">Bodega</option><option value="ranch">Rancho</option></select></Field>
    {propertyType !== 'land' && <Field label="Número de plantas"><select {...register('floors')}><option value="indifferent">Sin preferencia</option><option value="1">Una</option><option value="2">Dos</option><option value="3">Tres</option></select></Field>}
    {residential && <><Field label="Recámaras mínimas" error={errors.bedrooms?.message}><input type="number" min="0" max="15" {...register('bedrooms')} /></Field><Field label="Baños mínimos" error={errors.bathrooms?.message}><input type="number" step="0.5" min="0" max="15" {...register('bathrooms')} /></Field></>}
    {propertyType !== 'land' && <Field label="Estacionamientos mínimos"><input type="number" min="0" max="10" {...register('parking')} /></Field>}
    <Field label="Terreno mínimo (m²) — opcional"><input type="number" min="0" {...register('landAreaMin')} /></Field>{propertyType !== 'land' && <Field label="Construcción mínima (m²) — opcional"><input type="number" min="0" {...register('constructionAreaMin')} /></Field>}</div>
    {propertyType !== 'land' && <><p className="field-caption">Espacios indispensables</p><div className="checks-row"><Toggle label="Patio" {...register('yard')} /><Toggle label="Jardín" {...register('garden')} /><Toggle label="Alberca" {...register('pool')} /></div><fieldset><legend>Amenidades deseables — no obligatorias</legend><div className="checks-grid">{amenities.map(item => <label className="check" key={item}><input type="checkbox" value={item.toLowerCase()} {...register('amenities')} /><span>{item}</span></label>)}</div></fieldset></>}
    <details className="optional-details"><summary>Agregar detalles para la asesoría (opcional)</summary><p className="muted">Estas condiciones se compartirán si pides contacto. El asesor confirmará fechas, mascotas, pago y requisitos con el anunciante.</p>
    {type === 'rent' ? <div className="form-grid"><Field label="Fecha deseada de inicio"><input type="date" {...register('moveInDate')} /></Field><Field label="Duración del contrato (meses)"><input type="number" min="1" max="60" {...register('contractMonths')} /></Field><Field label="Número de inquilinos"><input type="number" min="1" max="30" {...register('tenants')} /></Field><Field label="Mobiliario"><select {...register('furnished')}><option value="indifferent">Sin preferencia</option><option value="furnished">Amueblado</option><option value="semi">Semiamueblado</option><option value="unfurnished">Sin muebles</option></select></Field><Toggle label="Tengo mascotas" {...register('hasPets')} />{hasPets && <Field label="Cantidad, raza y tamaño de las mascotas" error={errors.petDetails?.message}><input {...register('petDetails')} /></Field>}<Field label="Garantía disponible"><select {...register('guarantee')}><option value="advice">Necesito orientación</option><option value="guarantor">Aval</option><option value="legal_policy">Póliza jurídica</option><option value="deposit">Depósito</option></select></Field><Toggle label="Requiero facturación" {...register('invoiceRequired')} /></div> : <div className="form-grid"><Field label="Entrega deseada"><select {...register('delivery')}><option value="indifferent">Sin preferencia</option><option value="immediate">Inmediata</option><option value="presale">Preventa</option></select></Field><Field label="Forma de pago"><select {...register('paymentMethod')}><option value="credit">Crédito</option><option value="cash">Contado</option><option value="mixed">Combinación</option></select></Field>{payment !== 'cash' && <><Toggle label="Crédito preaprobado" {...register('creditPreapproved')} /><CurrencyField form={form} name="creditAmount" label="Monto estimado del crédito (MXN)" /></>}</div>}</details>
  </div>;
}

export function StepLocation({ form, type }: { form: UseFormReturn<LeadForm>; type: TransactionType }) {
  const { register, formState: { errors } } = form;
  return <div><span className="section-kicker">Ubicación y presupuesto</span><h2>¿Dónde buscas y cuánto quieres invertir?</h2><p className="muted">Los precios se comparan en pesos mexicanos{type === 'rent' ? ' por mes' : ''}. Deja las colonias en blanco si deseas revisar todo el municipio.</p>
    <div className="form-grid"><Field label="Ciudad o municipio" error={errors.city?.message}><input {...register('city')} list="property-cities" placeholder="Ej. Boca del Río" /></Field><datalist id="property-cities"><option value="Veracruz" /><option value="Boca del Río" /><option value="Alvarado" /><option value="Medellín de Bravo" /><option value="Catemaco" /></datalist><Field label="Colonia o zona preferida — opcional"><input {...register('neighborhood1')} placeholder="Ej. Costa de Oro" /></Field><Field label="Otra colonia o zona — opcional"><input {...register('neighborhood2')} /></Field><Field label="Una tercera zona — opcional"><input {...register('neighborhood3')} /></Field><CurrencyField form={form} name="budgetMin" label={'Presupuesto mínimo ' + (type === 'rent' ? 'mensual ' : '') + '(MXN) — opcional'} /><CurrencyField form={form} name="budgetMax" label={'Presupuesto máximo ' + (type === 'rent' ? 'mensual ' : '') + '(MXN)'} /></div>
    <details className="optional-details"><summary>Añadir otras prioridades (opcional)</summary><div className="form-grid"><Field label="Otras características indispensables" hint="Separa cada una con una coma. Si no aparece en el anuncio, quedará por confirmar."><textarea rows={3} {...register('essentialText')} placeholder="Ej. estudio, acceso sin escaleras" /></Field><Field label="Características que sería bueno tener"><textarea rows={3} {...register('desirableText')} placeholder="Ej. terraza, vista abierta" /></Field><Field label="Comentarios para el asesor"><textarea rows={3} {...register('comments')} /></Field></div></details>
  </div>;
}

export function StepReview({ form, type }: { form: UseFormReturn<LeadForm>; type: TransactionType }) {
  const values = form.getValues();
  const residential = ['house', 'apartment'].includes(values.propertyType);
  return <div><span className="section-kicker">Revisión</span><h2>Revisa tu búsqueda antes de ver las opciones</h2><div className="summary-grid"><Summary title="Operación e inmueble" value={(type === 'rent' ? 'Renta' : 'Compra') + ' de ' + labelProperty(values.propertyType).toLowerCase()} /><Summary title="Ubicación" value={[values.city, [values.neighborhood1, values.neighborhood2, values.neighborhood3].filter(Boolean).join(', ') || 'Todo el municipio'].join(' · ')} /><Summary title={type === 'rent' ? 'Presupuesto mensual (MXN)' : 'Presupuesto (MXN)'} value={money.format(values.budgetMin || 0) + ' a ' + money.format(values.budgetMax || 0)} /><Summary title="Mínimos indispensables" value={residential ? values.bedrooms + ' recámaras · ' + values.bathrooms + ' baños · ' + values.parking + ' estacionamientos' : [values.landAreaMin ? values.landAreaMin + ' m² de terreno' : '', values.constructionAreaMin ? values.constructionAreaMin + ' m² de construcción' : ''].filter(Boolean).join(' · ') || 'Sin metraje mínimo'} /></div>
    {[values.yard ? 'Patio' : '', values.garden ? 'Jardín' : '', values.pool ? 'Alberca' : '', values.essentialText].filter(Boolean).length > 0 && <p><strong>También indispensable: </strong>{[values.yard ? 'Patio' : '', values.garden ? 'Jardín' : '', values.pool ? 'Alberca' : '', values.essentialText].filter(Boolean).join(', ')}</p>}
    <div className="notice"><strong>Qué recibirás</strong><p>Coincidencias con datos publicados y, si las hay, alternativas con otro precio, ubicación o características. Podrás abrir los anuncios y elegir los que te interesen. Tus datos de contacto se pedirán solo si decides solicitar asesoría.</p></div><input className="honeypot" aria-label="Dejar vacío" tabIndex={-1} autoComplete="off" {...form.register('website')} />
  </div>;
}
