import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { randomUUID } from 'node:crypto';
import { z } from 'zod';
import { createClient } from '@supabase/supabase-js';
import OpenAI from 'openai';
import { Resend } from 'resend';

const app=express(); const port=Number(process.env.PORT||10000);
app.set('trust proxy',1); app.use(helmet({contentSecurityPolicy:false})); app.use(cors()); app.use(express.json({limit:'1mb'})); app.use('/api',rateLimit({windowMs:60_000,limit:60}));
const db=process.env.SUPABASE_URL&&process.env.SUPABASE_SERVICE_ROLE_KEY?createClient(process.env.SUPABASE_URL,process.env.SUPABASE_SERVICE_ROLE_KEY,{auth:{persistSession:false}}):null;
const ai=process.env.OPENAI_API_KEY?new OpenAI({apiKey:process.env.OPENAI_API_KEY}):null;
const mail=process.env.RESEND_API_KEY?new Resend(process.env.RESEND_API_KEY):null;
const cache=new Map<string,unknown>();

const schema=z.object({transactionType:z.enum(['rent','buy']),fullName:z.string().min(3),email:z.string().email(),phone:z.string().min(8),propertyType:z.enum(['house','apartment','land']),city:z.string().min(2),neighborhoods:z.array(z.string()).default([]),budgetMin:z.coerce.number().min(0),budgetMax:z.coerce.number().positive(),bedrooms:z.coerce.number().min(0).default(0),bathrooms:z.coerce.number().min(0).default(0),parking:z.coerce.number().min(0).default(0),yard:z.boolean().default(false),garden:z.boolean().default(false),pool:z.boolean().default(false),privacyAccepted:z.literal(true),contactAccepted:z.literal(true),essentialFeatures:z.array(z.string()).default([]),desirableFeatures:z.array(z.string()).default([]),website:z.string().max(0).default('')}).passthrough().refine(v=>v.budgetMax>=v.budgetMin,{message:'Presupuesto incoherente'});
type Lead=z.infer<typeof schema>;
type Property={id:string;title:string;transactionType:'rent'|'buy';propertyType:'house'|'apartment'|'land';city:string;neighborhood:string;price:number;bedrooms:number;bathrooms:number;parking:number;landArea:number;constructionArea:number;yard:boolean;garden:boolean;pool:boolean;amenities:string[];sourceName:string;sourceUrl:string;demo:boolean};
const demo:Property[]=[{id:'r1',title:'Casa familiar con estudio',transactionType:'rent',propertyType:'house',city:'Boca del Río',neighborhood:'Virginia',price:24000,bedrooms:3,bathrooms:2.5,parking:2,landArea:180,constructionArea:210,yard:true,garden:false,pool:false,amenities:['estudio','seguridad'],sourceName:'Catálogo demo',sourceUrl:'#',demo:true},{id:'b1',title:'Departamento con amenidades',transactionType:'buy',propertyType:'apartment',city:'Boca del Río',neighborhood:'Costa de Oro',price:3200000,bedrooms:3,bathrooms:2,parking:2,landArea:0,constructionArea:145,yard:false,garden:false,pool:true,amenities:['elevador','seguridad'],sourceName:'Catálogo demo',sourceUrl:'#',demo:true},{id:'b2',title:'Casa con jardín',transactionType:'buy',propertyType:'house',city:'Veracruz',neighborhood:'Reforma',price:2800000,bedrooms:3,bathrooms:2.5,parking:2,landArea:220,constructionArea:190,yard:true,garden:true,pool:false,amenities:['estudio'],sourceName:'Catálogo demo',sourceUrl:'#',demo:true}];
const norm=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
function rank(p:Property,l:Lead){if(p.transactionType!==l.transactionType)return null;let n=100;const reasons:string[]=[];const gaps:string[]=[];if(p.propertyType!==l.propertyType){n-=25;gaps.push('Tipología distinta')}else reasons.push('Tipología solicitada');if(norm(p.city)!==norm(l.city)){n-=35;gaps.push('Ciudad distinta')}else reasons.push('Ciudad solicitada');if(l.neighborhoods.length&&!l.neighborhoods.some(x=>norm(x)===norm(p.neighborhood))){n-=15;gaps.push('Colonia distinta')}if(p.price>l.budgetMax){const over=(p.price-l.budgetMax)/l.budgetMax;n-=Math.min(55,Math.round(over*100));gaps.push(`Supera el presupuesto en ${Math.round(over*100)}%`)}else reasons.push('Dentro del presupuesto');if(p.bedrooms<l.bedrooms){n-=20;gaps.push('Menos recámaras')}else reasons.push('Recámaras suficientes');if(p.bathrooms<l.bathrooms)n-=10;if(l.pool&&!p.pool)n-=15;if(l.garden&&!p.garden)n-=10;if(l.yard&&!p.yard)n-=8;return {...p,matchScore:Math.max(0,n),reasons,gaps,availabilityLabel:p.demo?'Propiedad ficticia para demostración':'Disponibilidad por confirmar'}}
function baseAnalysis(l:Lead,m:any[]){const difficult=l.bedrooms>=4||l.pool||l.neighborhoods.length>=2;return {viability:m.length?'high':difficult?'low':'medium',headline:m.length?'Encontramos opciones compatibles':'La combinación actual necesita ajustes',explanation:m.length?'Existen propiedades con compatibilidad razonable. El asesor confirmará disponibilidad y condiciones.':'No aparece una coincidencia suficiente en las fuentes configuradas. Conviene flexibilizar uno o dos criterios.',pressurePoints:m.length?[]:['El presupuesto, la ubicación y las características no coinciden simultáneamente con el inventario.'],suggestions:['Ampliar las colonias o zonas aceptadas','Aumentar el presupuesto máximo alrededor de 15%','Reducir una recámara si no es indispensable','Considerar otra tipología de inmueble'],advisorSummary:`Busca ${l.transactionType==='rent'?'renta':'compra'} de ${l.propertyType} en ${l.city}, máximo ${l.budgetMax} MXN.`}}
async function explain(l:Lead,base:any){if(!ai)return base;try{const r=await ai.responses.create({model:process.env.OPENAI_MODEL||'gpt-4.1-mini',store:false,input:`Redacta un diagnóstico inmobiliario breve en JSON sin inventar datos. Criterios: ${JSON.stringify({type:l.transactionType,property:l.propertyType,city:l.city,budget:l.budgetMax,bedrooms:l.bedrooms})}. Base: ${JSON.stringify(base)}`});return {...base,...JSON.parse(r.output_text)}}catch{return base}}
async function inventory(){if(!db)return demo;const {data,error}=await db.from('properties').select('*').eq('active',true).limit(500);if(error||!data)return demo;return data.map((p:any)=>({id:p.id,title:p.title,transactionType:p.transaction_type,propertyType:p.property_type,city:p.city,neighborhood:p.neighborhood,price:Number(p.price),bedrooms:Number(p.bedrooms),bathrooms:Number(p.bathrooms),parking:Number(p.parking),landArea:Number(p.land_area),constructionArea:Number(p.construction_area),yard:p.yard,garden:p.garden,pool:p.pool,amenities:p.amenities||[],sourceName:p.source_name,sourceUrl:p.source_url,demo:p.demo}))}
function links(l:Lead){const q=encodeURIComponent(`${l.propertyType} ${l.city} ${l.neighborhoods.join(' ')} ${l.bedrooms} recámaras ${l.budgetMax} MXN`);return [{name:'Inmuebles24',url:`https://www.google.com/search?q=site%3Ainmuebles24.com+${q}`},{name:'Vivanuncios',url:`https://www.google.com/search?q=site%3Avivanuncios.com.mx+${q}`},{name:'Facebook Marketplace',url:`https://www.facebook.com/marketplace/search/?query=${q}`}]} 
app.get('/api/health',(_q,s)=>s.json({ok:true,mode:db?'production':'demo'}));
app.post('/api/leads',async(q,s)=>{const key=String(q.header('Idempotency-Key')||'');if(!key)return s.status(400).json({error:'Falta Idempotency-Key'});if(cache.has(key))return s.json({...cache.get(key) as object,duplicate:true});const parsed=schema.safeParse(q.body);if(!parsed.success)return s.status(400).json({error:'Datos incompletos o incoherentes',issues:z.flattenError(parsed.error)});const lead=parsed.data;const matches=(await inventory()).map(p=>rank(p,lead)).filter(Boolean).filter((m:any)=>m.matchScore>=65&&m.price<=lead.budgetMax*1.1).sort((a:any,b:any)=>b.matchScore-a.matchScore).slice(0,8);const analysis=await explain(lead,baseAnalysis(lead,matches));const result={leadId:randomUUID(),duplicate:false,analysisSource:ai?'openai':'deterministic',metrics:{completeness:90,rigidity:lead.pool||lead.neighborhoods.length>=2?'high':'medium',contradictions:[]},analysis,matches,externalSearchLinks:links(lead),message:'Muchas gracias por aceptar nuestras políticas. En breve estaremos en contacto contigo.',disclaimer:'Precios, disponibilidad y condiciones deben confirmarse con el anunciante o asesor.'};cache.set(key,result);if(db)void db.from('leads').insert({id:result.leadId,idempotency_key:key,transaction_type:lead.transactionType,full_name:lead.fullName,email:lead.email,phone:lead.phone,city:lead.city,budget_min:lead.budgetMin,budget_max:lead.budgetMax,status:matches.length?'with_matches':'without_matches',payload:lead,response_payload:result,consent_at:new Date().toISOString()});if(mail)void mail.emails.send({from:process.env.EMAIL_FROM||'Círculo Inmobiliario <onboarding@resend.dev>',to:process.env.ADVISOR_EMAIL||'patyestr@hotmail.com',subject:`Nueva solicitud: ${lead.fullName}`,html:`<h1>Nueva solicitud inmobiliaria</h1><p>${lead.fullName} · ${lead.email} · ${lead.phone}</p><p>${analysis.advisorSummary}</p><p>${matches.length} coincidencias.</p>`});return s.status(201).json(result)});
const dir=path.dirname(fileURLToPath(import.meta.url));const publicDir=path.resolve(dir,'../../client/dist');app.use(express.static(publicDir));app.get('*',(_q,s)=>s.sendFile(path.join(publicDir,'index.html')));app.listen(port,()=>console.log(`Servidor activo en ${port}`));
